#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from petsys import daqd, config, fe_power
import pandas
import os
import stat
import argparse
import math
import glob

def parseArguments():
	parser = argparse.ArgumentParser(description='Acquire SIPM data from the DAQ system')
	# --- Required Arguments ---
	parser.add_argument("--config", type=str, required=True, help="Configuration file")
	parser.add_argument("-o", type=str, dest="fileNamePrefix", required=True, help="Output data filename prefix. If --enable-realtime-processing is set, a suffix identifying the output data type will be added.")
	parser.add_argument("--time", type=float, required=True, help="Acquisition time (in seconds)")
	parser.add_argument("--mode", type=str, required=True, choices=["tot", "qdc", "mixed"], help="Acquisition mode (tot, qdc or mixed)")
	# --- Boolean Flags ---
	parser.add_argument("--enable-hw-trigger", dest="hwTrigger", action="store_true", help="Enable the hardware coincidence filter")
	parser.add_argument('--enable-realtime-processing', dest="enableOnlineProcessing", action='store_true', help='Enable online (real-time) data processing.')
	parser.add_argument("--write-raw-data", default=False, dest="writeRaw", action="store_true", help="If --enable-realtime-processing is set, write a raw data file. Default: %(default)s.")
	# --- Conditional Processing Arguments (Kept optional for parsing) ---
	parser.add_argument("--output-type", type=str, dest="outputType", choices=["raw", "singles", "groups", "coincidences"], help="Selects the type output processed (Required if --enable-realtime-processing is set).")
	parser.add_argument("--output-format", type=str, dest="outputFormat", choices=["text", "textCompact", "binary", "binaryCompact", "root"], help="Selects the format of the output processed data (Required if --enable-realtime-processing is set).")
	parser.add_argument("--write-fraction", type=float, default=100.0, dest="writeFraction", help="Selects the fraction of events (0.0 to 100.0) to be written. Default: %(default)s.")
	parser.add_argument("--write-multiple-hits", type=int, default=1, dest="writeMultipleHits", help="Selects the number of hits to be written if output type is 'groups' or 'coincidences'. Default: %(default)s.")
	parser.add_argument("--timeref", type=str, default="sync", dest="timeRef", choices=["sync", "wall", "step", "manual"], help="Selects the time reference for timestamps. Default: %(default)s. If 'manual' is selected, the user must provide a time reference using --user-timeref.")
	parser.add_argument("--user-timeref", type=float, default=0, dest="userTimeRef", help="Defines the chosen user Wall time reference if --timeref is 'wall'. Default: %(default)s.")
	# --- Optional Hardware / Environment Parameters ---
	parser.add_argument("--param-table", type=str, dest="paramTable", help="Table containing the name and values of 1 or 2 parameters to be scanned (OV, vth_t1, etc.).")
	parser.add_argument("--wait-on", dest="waitOn", type=str, help="Wait for named pipe signal before starting.")
	parser.add_argument("--stop-on", dest="stopOn", type=str, default=None, help="Stop acquisition on named pipe signal.")
	parser.add_argument("--portID", type=int, help="Set target FEBD port ID")
	parser.add_argument("--slaveID", type=int, help="Set target FEBD slave ID")
	args = parser.parse_args()
	
	if args.enableOnlineProcessing:
		if not args.outputType:
			parser.error("The following argument is required when --enable-realtime-processing is set: --output-type")
		if not args.outputFormat:
			parser.error("The following argument is required when --enable-realtime-processing is set: --output-format")
	if args.timeRef == "wall" and args.userTimeRef is None:
		parser.error("--user-timeref must be provided when --timeref is set to 'wall'")

	return args


def checkRequiredArgs(parser, required_args, conditional_args):
	args, _ = parser.parse_known_args()
	if getattr(args, "enableOnlineProcessing"):
		for arg in required_args:
			if not getattr(args, arg):
				parser.error(f"--{arg} is required when --enable-realtime-processing is set")
	if not getattr(args, "enableOnlineProcessing"):
		for arg in conditional_args:
			if getattr(args, arg):
				parser.error(f"--{arg} is not allowed when --enable-realtime-processing is not set")


def validateFifo(path):
	if not os.path.exists(path):
		print(f"Error: '{path}' does not exist. Create it with: mkfifo {path}")
		exit(1)
	if not stat.S_ISFIFO(os.stat(path).st_mode):
		print(f"Error: '{path}' exists but is not a named pipe (FIFO). Create it with: mkfifo {path}")
		exit(1)


def main():
	args = parseArguments()

	validParams = ["OV","vth_t1","vth_t2","vth_e","disc_lsb_t1"]
	if args.paramTable is not None:
		if not os.path.exists(args.paramTable):
			print("Error: no such file - %s" % args.paramTable)
			exit(1)
		table = pandas.read_table(args.paramTable)
		parNames = list(table)
		for name in parNames:
			if name not in validParams:
				print(("Error: Invalid parameter - %s" % name))
				exit(1)

		step1Values = list(table[parNames[0]])
		if len(parNames) == 2:
			step2Values = list(table[parNames[1]])
		elif len(parNames) == 1:
			step2Values = [0]
			parNames.append("none")
		else:
			print("Error: only two parameters can be scanned at the same time")
			exit(1)

	mask = config.LOAD_ALL
	if args.mode != "mixed":
		mask ^= config.LOAD_QDCMODE_MAP

	if not args.hwTrigger:
		mask ^= config.LOAD_FIRMWARE_QDC_CALIBRATION

	systemConfig = config.ConfigFromFile(args.config, loadMask=mask)
	conn = daqd.Connection()

	if (args.portID != None and args.slaveID != None):
		for p, s in conn.getActiveFEBDs():
			fe_power.set_fem_power(conn,p,s,"off")  
		conn.initializeSystem(power_lst = [(args.portID,args.slaveID)])
	else:
		conn.initializeSystem()
	
	systemConfig.loadToHardware(conn, bias_enable=config.APPLY_BIAS_ON, hw_trigger_enable=args.hwTrigger, qdc_mode = args.mode)

	if args.waitOn:
		validateFifo(args.waitOn)
		conn.waitOnNamedPipe(args.waitOn)
	if args.stopOn:
		validateFifo(args.stopOn)

# if using online processing, perform a data transmission check before opening file for writing
	if not args.enableOnlineProcessing:
		conn.openRawAcquisition(args.fileNamePrefix)
	else:
		testFileName = os.path.dirname(args.fileNamePrefix)+"/checkDataTransmissionFile"
		if args.writeRaw:
			conn.openRawAcquisitionWithProcessing(testFileName,args.config, args.outputType, args.outputFormat, args.writeFraction, args.writeMultipleHits, args.timeRef, args.userTimeRef, verbose=False)
			if not conn.checkDataTransmission(args.time):
				exit(1)
			conn.openRawAcquisitionWithProcessing(args.fileNamePrefix,args.config, args.outputType, args.outputFormat, args.writeFraction, args.writeMultipleHits, args.timeRef, args.userTimeRef)
		else:
			conn.openAcquisitionWithProcessing(testFileName, args.config, args.outputType, args.outputFormat, args.writeFraction, args.writeMultipleHits, args.timeRef, args.userTimeRef, verbose=False)
			if not conn.checkDataTransmission(args.time):
				exit(1)
			conn.openAcquisitionWithProcessing(args.fileNamePrefix, args.config, args.outputType, args.outputFormat, args.writeFraction, args.writeMultipleHits, args.timeRef, args.userTimeRef)
		for file_path in glob.glob(testFileName + "*"):
			if os.path.isfile(file_path):
				os.remove(file_path)
	

	activeAsics = conn.getActiveAsics()
	activeChannels = [ (portID, slaveID, chipID, channelID) for channelID in range(64) for portID, slaveID, chipID in activeAsics ]
	asicsConfig = conn.getAsicsConfig()

	if args.paramTable is None:
		conn.acquire(args.time, 0, 0, args.stopOn)
	else:
		for step1 in step1Values:
			step1 = float(step1)
			if math.isnan(step1):
				continue
			if parNames[0] in ['vth_t1', 'vth_t2', 'vth_e']:
				for portID, slaveID, chipID, channelID in activeChannels:
					cc = asicsConfig[(portID, slaveID, chipID)].channelConfig[channelID]
					dac_setting = systemConfig.mapAsicChannelThresholdToDAC((portID, slaveID, chipID, channelID), parNames[0], int(step1))
					cc.setValue(parNames[0], dac_setting)
			elif parNames[0] in ['disc_lsb_t1']:
				for portID, slaveID, chipID in activeAsics:
					cc = asicsConfig[(portID, slaveID, chipID)].globalConfig
					cc.setValue(parNames[0], int(step1))
			elif parNames[0] in ['OV']:
				biasVoltageConfig = conn.get_hvdac_config()
				for key in conn.getActiveBiasChannels():
					offset, prebd, bd, over__ = systemConfig.getBiasChannelDefaultSettings(key)
					vset = offset + bd + step1
					dac_setting = systemConfig.mapBiasChannelVoltageToDAC(key, vset)
					biasVoltageConfig[key] = dac_setting
					conn.set_hvdac_config(biasVoltageConfig)
			conn.setAsicsConfig(asicsConfig)

			for step2 in step2Values:
				step2 = float(step2)
				if math.isnan(step2):
					continue
				if parNames[1] in ['vth_t1', 'vth_t2', 'vth_e']:
					for portID, slaveID, chipID, channelID in activeChannels:
						cc = asicsConfig[(portID, slaveID, chipID)].channelConfig[channelID]
						dac_setting = systemConfig.mapAsicChannelThresholdToDAC((portID, slaveID, chipID, channelID), parNames[1], int(step2))
						cc.setValue(parNames[1], dac_setting)
				elif parNames[1] in ['disc_lsb_t1']:
					for portID, slaveID, chipID in activeAsics:
						cc = asicsConfig[(portID, slaveID, chipID)].globalConfig
						cc.setValue(parNames[1], int(step2))
				elif parNames[1] in ['OV']:
					#step2 = step2_
					biasVoltageConfig = conn.get_hvdac_config()
					for key in conn.getActiveBiasChannels():
						offset, prebd, bd, over__ = systemConfig.getBiasChannelDefaultSettings(key)
						vset = offset + bd + step2
						dac_setting = systemConfig.mapBiasChannelVoltageToDAC(key, vset)
						biasVoltageConfig[key] = dac_setting
					conn.set_hvdac_config(biasVoltageConfig)

				if parNames[1] == "none":
					print("Python:: Acquiring data for: " + parNames[0] + " = " + str(step1))
				else:
					print("Python:: Acquiring data for: " + parNames[0] + " = " + str(step1) + " ; " + parNames[1] + " = " + str(step2))
				conn.setAsicsConfig(asicsConfig)
				conn.acquire(args.time, float(step1), float(step2), args.stopOn)

	systemConfig.loadToHardware(conn, bias_enable=config.APPLY_BIAS_OFF)
	return 0

if __name__ == '__main__':
	exit(main())
