#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from petsys import daqd
import argparse

def main():
    parser = argparse.ArgumentParser(description='Make a channel and trigger map for UVic teststand')
    parser.add_argument("-o", type=str, required=True, help="Output file")
    args = parser.parse_args()

    channelOutputFile = open(args.o + "_channel.tsv", "w")
    triggerOutputFile = open(args.o + "_trigger.tsv", "w")

    connection = daqd.Connection()
    connection.initializeSystem(skipFEM=True)

    # [channelA, channelB]
    coincident_list = [ [0,14],   [1,7],  [2,15],  [3,12],  [4,27],  [5,10],  [6,11],  [8,13],
                        [9,50], [16,22], [17,20], [18,23], [19,21], [24,31], [25,32], [26,30],
                       [28,29], [33,41], [34,40], [35,37], [36,39], [38,57], [42,48], [43,49],
                       [44,47], [45,46], [51,60], [52,63], [53,56], [54,55], [58,61], [59,62]]

    # [channel, xi, yi]
    region_list = [[0,1,0],   [1,1,1],  [2,2,3],  [3,0,1],
                   [4,0,2],   [5,3,0],  [6,0,3],  [7,2,1],
                   [8,1,2],   [9,3,4], [10,0,0], [11,3,3],
                   [12,3,1], [13,2,2], [14,2,0], [15,1,3],
                   [16,6,1], [17,7,0], [18,6,0], [19,7,1],
                   [20,4,0], [21,4,1], [22,5,1], [23,5,0],
                   [24,7,3], [25,7,2], [26,6,3], [27,3,2],
                   [28,6,2], [29,5,2], [30,5,3], [31,4,3],
                   [32,4,2], [33,4,4], [34,4,5], [35,5,5],
                   [36,5,4], [37,6,5], [38,3,5], [39,6,4],
                   [40,7,5], [41,7,4], [42,4,7], [43,4,6],
                   [44,5,7], [45,6,6], [46,5,6], [47,6,7],
                   [48,7,7], [49,7,6], [50,0,4], [51,3,7],
                   [52,3,6], [53,2,6], [54,2,7], [55,1,7],
                   [56,1,6], [57,0,5], [58,2,5], [59,1,4],
                   [60,0,7], [61,1,5], [62,2,4], [63,0,6]]

    #write channel map with columns: portID, slaveID chipID, channelID, regionID, xi, yi, x, y, z
    channelOutputFile.write("#portID\tslaveID\tchipID\tchannelID\tregionID\txi\tyi\tx\ty\tz\n")
    for portID, slaveID in connection.getActiveFEBDs():
        for chipID in range(16):
            for channelID in range(64):
                regionID = region_list[channelID][0]
                xi = region_list[channelID][1]
                yi = region_list[channelID][2]
                channelOutputFile.write(f"{portID}\t{slaveID}\t{chipID}\t{channelID}\t{regionID}\t{xi}\t{yi}\t{0}\t{0}\t{0}\n")

    #write trigger map with columns: regionID, regionID, trigger_type
    for channelPair in coincident_list:
        triggerOutputFile.write(f"{channelPair[0]}\t{channelPair[1]}\tC\n")

    channelOutputFile.close()
    triggerOutputFile.close()
    
if __name__ == '__main__':
    main()
