#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import re
import uproot
import scipy
import numpy as np
import matplotlib.pyplot as plt

channelIDs = np.arange(0, 64, 1)
timeInt = 0.1
t1TargetRate = 100e3
t1TargetNPE = 0.5       # target number of photoelectrons to cut on
t2TargetRate = 10e3
t2TargetNPE = 1.5       # actually 2.0, because up to 0.5 is already cut out by the t1 values
eTargetRate = 1e3
eTargetNPE = 2.5        # actually 4.5, because up to 2.0 is already cut


def normalize(l):
    l = re.sub(r"\s*#.*", "", l)# Remove comments
    l = re.sub(r"^\s*", '', l)  # Remove leading white space
    l = re.sub(r"\s*$", '', l)  # Remove trailing whitespace
    l = re.sub(r"\s+", '\t', l) # Normalize whitespace to tabs
    l = re.sub('\r', '', l)     # Remove \r
    l = re.sub('\n', '', l)     # Remove \n
    return l


def set_thresholds(hits, steps, target_npe, target_rate, param, colours, outputDirectory):
    thresholds = []
    for ch in channelIDs:
        ch_rate = hits[ch]/timeInt                      # calculate the rate of hits per step
        ch_err = np.sqrt(hits[ch])/timeInt              # calculate the error on the rate of hits per step
        ch_trigger_rate = np.array(ch_rate)             # calculate the trigger rate of hits per step (for smoothing)
        ch_trigger_rate[ch_trigger_rate <= 0] = 1e-10   # to avoid log10(0) errors

        ch_trigger_rate_diff = -scipy.ndimage.gaussian_filter(np.log10(ch_trigger_rate), sigma=1.2, order=1)    # smoothes the function
        ch_trigger_rate_curve = scipy.interpolate.interp1d(steps, ch_trigger_rate_diff, kind="quadratic")       # creates a function that can be used to find the value of points in the function that aren't in the array
        ch_thresholds_interp = np.linspace(steps[0], steps[-1], 512)                                            # creates an array of 512 points between the first and last step
        ch_rate_inter = ch_trigger_rate_curve(ch_thresholds_interp)                                             # finds the value of points in the function that aren't in the array
        ch_peaks, ch_prop = scipy.signal.find_peaks(ch_rate_inter, height=0.1, prominence=0.001)                # finds the steps

        if len(ch_peaks) < int(target_npe) or len(ch_peaks) == int(target_npe):
            print(f"Channel {ch}: Not enough peaks found. Setting to minimum.")
            ch_baseline = min(steps)
            ch_centred = min(steps)
        else:
            print(f"Channel {ch}: Found {len(ch_peaks)} peaks.")
            ch_baseline = int(ch_thresholds_interp[ch_peaks[int(target_npe)]])  # finds the end of the target npe peak
            ch_centred = int(ch_baseline) - 2                                   # roughly centres it

        thresholds.append(int(ch_centred))
        fig, ax = plt.subplots()
        ax.errorbar(steps, ch_rate, yerr=ch_err, color=colours[0], fmt='o', ecolor=colours[0], barsabove=False)
        ax.set_yscale('log')
        ax.set_ylabel('Rate')
        ax.set_xlabel(f'{param} Threshold')
        ax.set_title(f'Channel {ch} {param} Scan')
        ax.axvline(x=ch_centred, color=colours[1], label = f'Optimal Threshold: {ch_centred}')
        ax.axhline(y=target_rate, color=colours[2], label = f'Target Rate: {target_rate}')
        ax.grid(color = 'whitesmoke', linestyle = '--')
        ax.legend()
        plt.savefig(f'{outputDirectory}/ch{ch}_{param}_scan.png', dpi=300, bbox_inches='tight')
        plt.close(fig)
    return thresholds


def main():
    parser = argparse.ArgumentParser(description='Process a threshold scan, generate plots per channel')
    parser.add_argument("-i", type=str, dest="inputRootFile", required=True, help="Input root file prefix")
    parser.add_argument("-p", type=str, dest="parameterScanFile", required=True, help="Parameter scan file prefix")
    parser.add_argument("-o", type=str, dest="outputDirectory", required=True, help="Output directory for plots")
    args = parser.parse_args()

    inputScanFile = open(args.parameterScanFile + ".txt")
    scanSteps = []
    for i, line in enumerate(inputScanFile):
        line = normalize(line)
        if i == 0: scanParam = str(line)
        else: scanSteps.append(int(line))
    inputScanFile.close()

    scanFile = uproot.open(args.inputRootFile + ".root")
    activeSteps = scanFile["data"]["step1"].array().tolist()
    activeChan = scanFile["data"]["channelID"].array().tolist()
    energies = scanFile["data"]["energy"].array().tolist()

    # make 2D array of hits per step per channel: rows = channels (64), columns are steps (len(scanSteps))
    hitsPerStep = np.zeros((64, len(scanSteps)), dtype=int)
    for step, chan in zip(activeSteps, activeChan):
        stepIndex = scanSteps.index(step)
        hitsPerStep[chan][stepIndex] += 1

    print(f"Processing scan: {scanParam} = {scanSteps}") 
    print(scanFile["data"])

    t1Colours = ["darkolivegreen", "darkseagreen", "khaki"]
    t2Colours = ["teal", "cadetblue", "lightblue"]
    eColours = ["mediumvioletred", "lightcoral", "lightpink"]

    if scanParam == "vth_t1":
        vth_t1s = set_thresholds(hitsPerStep, scanSteps, t1TargetNPE, t1TargetRate, "vth_t1", t1Colours, args.outputDirectory)
    elif scanParam == "vth_t2":
        vth_t2s = set_thresholds(hitsPerStep, scanSteps, t2TargetNPE, t2TargetRate, "vth_t2", t2Colours, args.outputDirectory)
    elif scanParam == "vth_e":
        vth_es = set_thresholds(hitsPerStep, scanSteps, eTargetNPE, eTargetRate, "vth_e", eColours, args.outputDirectory)
    # elif scanParam == "OV":
    #     set_thresholds(scanData, scanSteps)
    # elif scanParam == "lsb_t1":
    #     set_thresholds(scanData, scanSteps)
    else:
        print("Invalid parameter to scan, idk how you even made this file with petsys")


if __name__ == '__main__':
    main()